"""add vote stages multistage

Revision ID: 4b1f2808576b
Revises: 819d510cbd34
Create Date: 2026-04-08 15:11:17.108324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b1f2808576b'
down_revision: Union[str, Sequence[str], None] = '819d510cbd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vote_session_id', sa.UUID(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('candidate_game_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('max_selections', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vote_session_id'], ['vote_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_session_id', 'stage_number', name='uq_stage_session_number')
    )
    op.create_index('ix_stage_session_status', 'vote_stages', ['vote_session_id', 'status'], unique=False)
    op.create_index(op.f('ix_vote_stages_vote_session_id'), 'vote_stages', ['vote_session_id'], unique=False)
    op.add_column('vote_ballots', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('uq_ballot_session_user'), 'vote_ballots', type_='unique')
    op.create_index(op.f('ix_vote_ballots_stage_id'), 'vote_ballots', ['stage_id'], unique=False)
    op.create_unique_constraint('uq_ballot_session_user_stage', 'vote_ballots', ['vote_session_id', 'user_id', 'stage_id'])
    op.create_foreign_key(None, 'vote_ballots', 'vote_stages', ['stage_id'], ['id'], ondelete='CASCADE')
    op.add_column('vote_sessions', sa.Column('tiebreak_seed', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('vote_sessions', sa.Column('current_stage_number', sa.Integer(), nullable=True))
    op.add_column('vote_sessions', sa.Column('total_stages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_sessions', 'total_stages')
    op.drop_column('vote_sessions', 'current_stage_number')
    op.drop_column('vote_sessions', 'tiebreak_seed')
    op.drop_constraint(None, 'vote_ballots', type_='foreignkey')
    op.drop_constraint('uq_ballot_session_user_stage', 'vote_ballots', type_='unique')
    op.drop_index(op.f('ix_vote_ballots_stage_id'), table_name='vote_ballots')
    op.create_unique_constraint(op.f('uq_ballot_session_user'), 'vote_ballots', ['vote_session_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vote_ballots', 'stage_id')
    op.drop_index(op.f('ix_vote_stages_vote_session_id'), table_name='vote_stages')
    op.drop_index('ix_stage_session_status', table_name='vote_stages')
    op.drop_table('vote_stages')
    # ### end Alembic commands ###
