"""add group current game

Revision ID: 819d510cbd34
Revises: f5a2fcb7932f
Create Date: 2026-04-08 14:15:16.087216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819d510cbd34'
down_revision: Union[str, Sequence[str], None] = 'f5a2fcb7932f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('current_game_id', sa.UUID(), nullable=True))
    op.add_column('groups', sa.Column('current_game_source', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('current_game_set_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('groups', sa.Column('current_game_set_by', sa.UUID(), nullable=True))
    op.add_column('groups', sa.Column('current_game_vote_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['current_game_set_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'groups', 'games', ['current_game_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'groups', 'vote_sessions', ['current_game_vote_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'current_game_vote_id')
    op.drop_column('groups', 'current_game_set_by')
    op.drop_column('groups', 'current_game_set_at')
    op.drop_column('groups', 'current_game_source')
    op.drop_column('groups', 'current_game_id')
    # ### end Alembic commands ###
