"""add group discord visuals

Revision ID: f5a2fcb7932f
Revises: 9f3e1c4a7b20
Create Date: 2026-04-08 13:58:13.282093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a2fcb7932f'
down_revision: Union[str, Sequence[str], None] = '9f3e1c4a7b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('splash_url', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('accent_color', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'description')
    op.drop_column('groups', 'accent_color')
    op.drop_column('groups', 'splash_url')
    op.drop_column('groups', 'banner_url')
    # ### end Alembic commands ###
