/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/discord/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discord Callback */
        post: operations["discord_callback_api_auth_discord_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_groups_get"];
        put?: never;
        /** Create Or Join Group */
        post: operations["create_or_join_group_api_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Group */
        get: operations["get_group_api_groups__group_id__get"];
        put?: never;
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_groups__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_groups__group_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Webhook */
        put: operations["update_webhook_api_groups__group_id__webhook_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave Group */
        delete: operations["leave_group_api_groups__group_id__leave_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/members/{target_user_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote Member */
        post: operations["promote_member_api_groups__group_id__members__target_user_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/members/{target_user_id}/demote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demote Member */
        post: operations["demote_member_api_groups__group_id__members__target_user_id__demote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_api_groups__group_id__games_get"];
        put?: never;
        /** Create Game */
        post: operations["create_game_api_groups__group_id__games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_groups__group_id__games__game_id__get"];
        put?: never;
        post?: never;
        /** Archive Game */
        delete: operations["archive_game_api_groups__group_id__games__game_id__delete"];
        options?: never;
        head?: never;
        /** Update Game */
        patch: operations["update_game_api_groups__group_id__games__game_id__patch"];
        trace?: never;
    };
    "/api/games/{game_id}/interest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Interest */
        put: operations["set_interest_api_games__game_id__interest_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Roster */
        post: operations["join_roster_api_games__game_id__roster_post"];
        /** Leave Roster */
        delete: operations["leave_roster_api_games__game_id__roster_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Toggle Ownership */
        put: operations["toggle_ownership_api_games__game_id__ownership_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Votes */
        get: operations["list_votes_api_groups__group_id__votes_get"];
        put?: never;
        /** Create Vote */
        post: operations["create_vote_api_groups__group_id__votes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/votes/{vote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vote */
        get: operations["get_vote_api_groups__group_id__votes__vote_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/votes/{vote_id}/ballot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Submit Ballot */
        put: operations["submit_ballot_api_votes__vote_id__ballot_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/votes/{vote_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Vote */
        post: operations["close_vote_api_groups__group_id__votes__vote_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Themes */
        get: operations["list_themes_api_groups__group_id__themes_get"];
        put?: never;
        /** Set Theme */
        post: operations["set_theme_api_groups__group_id__themes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/themes/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Theme */
        get: operations["get_current_theme_api_groups__group_id__themes_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/themes/{theme_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Theme */
        delete: operations["delete_theme_api_groups__group_id__themes__theme_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_groups__group_id__sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_groups__group_id__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_groups__group_id__sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_groups__group_id__sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_api_groups__group_id__sessions__session_id__patch"];
        trace?: never;
    };
    "/api/groups/{group_id}/sessions/{session_id}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rsvp Session */
        put: operations["rsvp_session_api_groups__group_id__sessions__session_id__rsvp_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/sessions/{session_id}/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Ics */
        get: operations["session_ics_api_groups__group_id__sessions__session_id__calendar_ics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/hardware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Hardware */
        put: operations["update_hardware_api_users_hardware_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Settings */
        get: operations["get_my_settings_api_users_me_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch My Settings */
        patch: operations["patch_my_settings_api_users_me_settings_patch"];
        trace?: never;
    };
    "/api/steam/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Steam Search */
        get: operations["steam_search_api_steam_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/steam/game/{appid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Steam Game */
        get: operations["steam_game_api_steam_game__appid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthTokenResponse */
        AuthTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /** BallotSubmit */
        BallotSubmit: {
            /** Approvals */
            approvals: string[];
        };
        /** DiscordCallbackRequest */
        DiscordCallbackRequest: {
            /** Code */
            code: string;
        };
        /** GameCreate */
        GameCreate: {
            /** Name */
            name: string;
            /** Steam Appid */
            steam_appid?: number | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Is Free
             * @default false
             */
            is_free: boolean;
            /** Price Current */
            price_current?: number | null;
            /**
             * Genres
             * @default []
             */
            genres: string[];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Player Min
             * @default 1
             */
            player_min: number;
            /** Player Max */
            player_max?: number | null;
            /** @default unknown */
            min_hardware_tier: components["schemas"]["HardwareTier"];
        };
        /**
         * GameStage
         * @enum {string}
         */
        GameStage: "exploring" | "campaign" | "endgame" | "paused" | "abandoned";
        /** GameUpdate */
        GameUpdate: {
            /** Name */
            name?: string | null;
            stage?: components["schemas"]["GameStage"] | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Description */
            description?: string | null;
            /** Player Min */
            player_min?: number | null;
            /** Player Max */
            player_max?: number | null;
            min_hardware_tier?: components["schemas"]["HardwareTier"] | null;
            /** Steam Appid */
            steam_appid?: number | null;
            /** Is Free */
            is_free?: boolean | null;
            /** Price Current */
            price_current?: number | null;
            /** Genres */
            genres?: string[] | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** GameViability */
        GameViability: {
            /** Price Score */
            price_score: number;
            /** Hardware Fit Percent */
            hardware_fit_percent: number;
            /** Interest Score */
            interest_score: number;
            /** Viability Score */
            viability_score: number;
            /** Interest Want Count */
            interest_want_count: number;
            /** Interest Ok Count */
            interest_ok_count: number;
            /** Interest Pass Count */
            interest_pass_count: number;
            /** Ownership Count */
            ownership_count: number;
        };
        /** GameWithViability */
        GameWithViability: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Group Id
             * Format: uuid
             */
            group_id: string;
            /** Name */
            name: string;
            /** Steam Appid */
            steam_appid?: number | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Description */
            description?: string | null;
            /** Is Free */
            is_free: boolean;
            /** Price Current */
            price_current?: number | null;
            /**
             * Genres
             * @default []
             */
            genres: string[];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Player Min */
            player_min: number;
            /** Player Max */
            player_max?: number | null;
            min_hardware_tier: components["schemas"]["HardwareTier"];
            stage: components["schemas"]["GameStage"];
            /**
             * Stage Updated At
             * Format: date-time
             */
            stage_updated_at: string;
            /** Created By */
            created_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Archived At */
            archived_at?: string | null;
            viability: components["schemas"]["GameViability"];
            user_interest?: components["schemas"]["InterestSignal"] | null;
            /**
             * User In Roster
             * @default false
             */
            user_in_roster: boolean;
            /**
             * User Owns Game
             * @default false
             */
            user_owns_game: boolean;
        };
        /** GroupCreate */
        GroupCreate: {
            /** Discord Guild Id */
            discord_guild_id: string;
            /** Name */
            name: string;
            /** Icon Url */
            icon_url?: string | null;
            /** Webhook Url */
            webhook_url?: string | null;
        };
        /** GroupMembershipResponse */
        GroupMembershipResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Group Id
             * Format: uuid
             */
            group_id: string;
            role: components["schemas"]["GroupRole"];
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            user?: components["schemas"]["UserResponse"] | null;
        };
        /** GroupResponse */
        GroupResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Discord Guild Id */
            discord_guild_id: string;
            /** Icon Url */
            icon_url?: string | null;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Webhook Url */
            webhook_url?: string | null;
            /** Budget Max */
            budget_max?: number | null;
            /**
             * Typical Party Size
             * @default 4
             */
            typical_party_size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * GroupRole
         * @description Role dentro de um grupo. Owner nao e role: e o user_id em group.owner_user_id.
         * @enum {string}
         */
        GroupRole: "admin" | "mod" | "member";
        /** GroupWithStats */
        GroupWithStats: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Discord Guild Id */
            discord_guild_id: string;
            /** Icon Url */
            icon_url?: string | null;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Webhook Url */
            webhook_url?: string | null;
            /** Budget Max */
            budget_max?: number | null;
            /**
             * Typical Party Size
             * @default 4
             */
            typical_party_size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /**
             * Game Count
             * @default 0
             */
            game_count: number;
            /**
             * Active Vote Sessions
             * @default 0
             */
            active_vote_sessions: number;
            /** @default member */
            user_role: components["schemas"]["GroupRole"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareResponse */
        HardwareResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            tier: components["schemas"]["HardwareTier"];
            /** Notes */
            notes?: string | null;
        };
        /**
         * HardwareTier
         * @enum {string}
         */
        HardwareTier: "low" | "mid" | "high" | "unknown";
        /** HardwareUpdate */
        HardwareUpdate: {
            tier: components["schemas"]["HardwareTier"];
            /** Notes */
            notes?: string | null;
        };
        /**
         * InterestSignal
         * @enum {string}
         */
        InterestSignal: "want" | "ok" | "pass";
        /** InterestSignalUpdate */
        InterestSignalUpdate: {
            signal: components["schemas"]["InterestSignal"];
        };
        /** OwnershipToggle */
        OwnershipToggle: {
            /** Owns */
            owns: boolean;
        };
        /** PromoteRequest */
        PromoteRequest: {
            new_role: components["schemas"]["GroupRole"];
        };
        /** RsvpResponse */
        RsvpResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            status: components["schemas"]["SessionRsvp"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RsvpUpdate */
        RsvpUpdate: {
            status: components["schemas"]["SessionRsvp"];
        };
        /** SessionCreate */
        SessionCreate: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * Duration Minutes
             * @default 60
             */
            duration_minutes: number;
            /** Max Participants */
            max_participants?: number | null;
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Group Id
             * Format: uuid
             */
            group_id: string;
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /** Created By */
            created_by: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Max Participants */
            max_participants: number | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Rsvp Yes
             * @default 0
             */
            rsvp_yes: number;
            /**
             * Rsvp No
             * @default 0
             */
            rsvp_no: number;
            /**
             * Rsvp Maybe
             * @default 0
             */
            rsvp_maybe: number;
            user_rsvp?: components["schemas"]["SessionRsvp"] | null;
            /**
             * Rsvps
             * @default []
             */
            rsvps: components["schemas"]["RsvpResponse"][];
        };
        /**
         * SessionRsvp
         * @enum {string}
         */
        SessionRsvp: "yes" | "no" | "maybe";
        /** SessionUpdate */
        SessionUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Start At */
            start_at?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Max Participants */
            max_participants?: number | null;
            /** Status */
            status?: string | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Timezone */
            timezone: string | null;
            /** Notification Email */
            notification_email: string | null;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Timezone */
            timezone?: string | null;
            /** Notification Email */
            notification_email?: string | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
        };
        /** ThemeCreate */
        ThemeCreate: {
            /** Theme Name */
            theme_name: string;
            /** Description */
            description?: string | null;
            /**
             * Month Year
             * @description YYYY-MM, default: mes atual
             */
            month_year?: string | null;
        };
        /** ThemeResponse */
        ThemeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Group Id
             * Format: uuid
             */
            group_id: string;
            /** Month Year */
            month_year: string;
            /** Theme Name */
            theme_name: string;
            /** Description */
            description: string | null;
            /** Decided By */
            decided_by: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Created By */
            created_by: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Discord Id */
            discord_id: string;
            /** Discord Username */
            discord_username: string;
            /** Discord Display Name */
            discord_display_name?: string | null;
            /** Discord Avatar */
            discord_avatar?: string | null;
            /** Discord Email */
            discord_email?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /** @default unknown */
            hardware_tier: components["schemas"]["HardwareTier"];
            /**
             * Steam Linked
             * @default false
             */
            steam_linked: boolean;
            /** Steam Id */
            steam_id?: string | null;
            /**
             * Is New User
             * @default false
             */
            is_new_user: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoteSessionCreate */
        VoteSessionCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Candidate Game Ids */
            candidate_game_ids: string[];
            /**
             * Duration Hours
             * @default 24
             */
            duration_hours: number;
        };
        /** VoteSessionResponse */
        VoteSessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Group Id
             * Format: uuid
             */
            group_id: string;
            /** Created By */
            created_by: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["VoteStatus"];
            /** Candidate Game Ids */
            candidate_game_ids: string[];
            /** Eligible Voter Count */
            eligible_voter_count: number;
            /** Quorum Count */
            quorum_count: number;
            /** Max Selections */
            max_selections: number;
            /**
             * Opens At
             * Format: date-time
             */
            opens_at: string;
            /** Closes At */
            closes_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Winner Game Id */
            winner_game_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Ballots Count
             * @default 0
             */
            ballots_count: number;
        };
        /**
         * VoteStatus
         * @enum {string}
         */
        VoteStatus: "open" | "closed" | "archived";
        /** WebhookUpdate */
        WebhookUpdate: {
            /** Webhook Url */
            webhook_url?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    discord_callback_api_auth_discord_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscordCallbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_groups_api_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupWithStats"][];
                };
            };
        };
    };
    create_or_join_group_api_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_group_api_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_groups__group_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMembershipResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_webhook_api_groups__group_id__webhook_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_group_api_groups__group_id__leave_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_member_api_groups__group_id__members__target_user_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                target_user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demote_member_api_groups__group_id__members__target_user_id__demote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                target_user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_groups__group_id__games_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameWithViability"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_game_api_groups__group_id__games_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameWithViability"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_groups__group_id__games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameWithViability"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_game_api_groups__group_id__games__game_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_game_api_groups__group_id__games__game_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameWithViability"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_interest_api_games__game_id__interest_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterestSignalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_roster_api_games__game_id__roster_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_roster_api_games__game_id__roster_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_ownership_api_games__game_id__ownership_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnershipToggle"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_votes_api_groups__group_id__votes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vote_api_groups__group_id__votes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vote_api_groups__group_id__votes__vote_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                vote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_ballot_api_votes__vote_id__ballot_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BallotSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_vote_api_groups__group_id__votes__vote_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                vote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_themes_api_groups__group_id__themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_theme_api_groups__group_id__themes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThemeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_theme_api_groups__group_id__themes_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_theme_api_groups__group_id__themes__theme_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                theme_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_groups__group_id__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_groups__group_id__sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_groups__group_id__sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_groups__group_id__sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_groups__group_id__sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rsvp_session_api_groups__group_id__sessions__session_id__rsvp_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RsvpUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_ics_api_groups__group_id__sessions__session_id__calendar_ics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hardware_api_users_hardware_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HardwareUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_settings_api_users_me_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    patch_my_settings_api_users_me_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    steam_search_api_steam_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    steam_game_api_steam_game__appid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
